In [28]:
#import libraries
try:
    import urllib2 as urllib
except ImportError:
    import urllib.request as urllib
import requests 
import pandas as pd
#import dask.dataframe as pd_dd
import zipfile
import io
import wget
from shapely.geometry import Point
import geopandas as gpd
import random
import json
from fiona.crs import from_epsg
#import pysal as ps
import pylab as pl
import matplotlib.pyplot as plt
from os import listdir
from os.path import isfile, join
import csv
import numpy as np

In [3]:
aff_path = r'C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1'
output_path = r'C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1'
aff_files = [f for f in listdir(aff_path) if isfile(join(aff_path, f))]
aff_txt = [x for x in aff_files if ".txt" in x]
aff_csv_meta = [x for x in aff_files  if ".csv" in x and "metadata" in x]
aff_csv = [x for x in aff_files  if ".csv" in x and "metadata" not in x ]

In [4]:
print(aff_txt)

['ACS_17_5YR_B01001.txt', 'ACS_17_5YR_B28002.txt', 'ACS_17_5YR_B28003.txt', 'ACS_17_5YR_B28004.txt', 'ACS_17_5YR_B28005.txt', 'ACS_17_5YR_B28006.txt', 'ACS_17_5YR_B28007.txt', 'ACS_17_5YR_B28008.txt', 'ACS_17_5YR_B28011.txt', 'ACS_17_5YR_B99281.txt', 'ACS_17_5YR_B99283.txt', 'ACS_17_5YR_DP02.txt', 'ACS_17_5YR_S0101.txt', 'ACS_17_5YR_S0501.txt', 'ACS_17_5YR_S0801.txt', 'ACS_17_5YR_S0802.txt', 'ACS_17_5YR_S0901.txt', 'ACS_17_5YR_S1101.txt', 'ACS_17_5YR_S1201.txt', 'ACS_17_5YR_S1301.txt', 'ACS_17_5YR_S1401.txt', 'ACS_17_5YR_S1501.txt', 'ACS_17_5YR_S1502.txt', 'ACS_17_5YR_S1601.txt', 'ACS_17_5YR_S1602.txt', 'ACS_17_5YR_S1603.txt', 'ACS_17_5YR_S1701.txt', 'ACS_17_5YR_S1810.txt', 'ACS_17_5YR_S1901.txt', 'ACS_17_5YR_S1902.txt', 'ACS_17_5YR_S1903.txt', 'ACS_17_5YR_S2001.txt', 'ACS_17_5YR_S2101.txt', 'ACS_17_5YR_S2201.txt', 'ACS_17_5YR_S2301.txt', 'ACS_17_5YR_S2302.txt', 'ACS_17_5YR_S2303.txt', 'ACS_17_5YR_S2501.txt', 'ACS_17_5YR_S2801.txt', 'ACS_17_5YR_S2802.txt', 'aff_download_readme_ann.txt']

In [5]:
print(aff_csv)

['ACS_17_5YR_B01001_with_ann.csv', 'ACS_17_5YR_B28002_with_ann.csv', 'ACS_17_5YR_B28003_with_ann.csv', 'ACS_17_5YR_B28004_with_ann.csv', 'ACS_17_5YR_B28005_with_ann.csv', 'ACS_17_5YR_B28006_with_ann.csv', 'ACS_17_5YR_B28007_with_ann.csv', 'ACS_17_5YR_B28008_with_ann.csv', 'ACS_17_5YR_B28011_with_ann.csv', 'ACS_17_5YR_B99281_with_ann.csv', 'ACS_17_5YR_B99283_with_ann.csv', 'ACS_17_5YR_DP02_with_ann.csv', 'ACS_17_5YR_S0101_with_ann.csv', 'ACS_17_5YR_S0501_with_ann.csv', 'ACS_17_5YR_S0801_with_ann.csv', 'ACS_17_5YR_S0802_with_ann.csv', 'ACS_17_5YR_S0901_with_ann.csv', 'ACS_17_5YR_S1101_with_ann.csv', 'ACS_17_5YR_S1201_with_ann.csv', 'ACS_17_5YR_S1301_with_ann.csv', 'ACS_17_5YR_S1401_with_ann.csv', 'ACS_17_5YR_S1501_with_ann.csv', 'ACS_17_5YR_S1502_with_ann.csv', 'ACS_17_5YR_S1601_with_ann.csv', 'ACS_17_5YR_S1602_with_ann.csv', 'ACS_17_5YR_S1603_with_ann.csv', 'ACS_17_5YR_S1701_with_ann.csv', 'ACS_17_5YR_S1810_with_ann.csv', 'ACS_17_5YR_S1901_with_ann.csv', 'ACS_17_5YR_S1902_with_ann.csv', 'ACS_17_5YR_S1903_with_ann.csv', 'ACS_17_5YR_S2001_with_ann.csv', 'ACS_17_5YR_S2101_with_ann.csv', 'ACS_17_5YR_S2201_with_ann.csv', 'ACS_17_5YR_S2301_with_ann.csv', 'ACS_17_5YR_S2302_with_ann.csv', 'ACS_17_5YR_S2303_with_ann.csv', 'ACS_17_5YR_S2501_with_ann.csv', 'ACS_17_5YR_S2801_with_ann.csv', 'ACS_17_5YR_S2802_with_ann.csv']

In [6]:
print(aff_csv_meta)

['ACS_17_5YR_B01001_metadata.csv', 'ACS_17_5YR_B28002_metadata.csv', 'ACS_17_5YR_B28003_metadata.csv', 'ACS_17_5YR_B28004_metadata.csv', 'ACS_17_5YR_B28005_metadata.csv', 'ACS_17_5YR_B28006_metadata.csv', 'ACS_17_5YR_B28007_metadata.csv', 'ACS_17_5YR_B28008_metadata.csv', 'ACS_17_5YR_B28011_metadata.csv', 'ACS_17_5YR_B99281_metadata.csv', 'ACS_17_5YR_B99283_metadata.csv', 'ACS_17_5YR_DP02_metadata.csv', 'ACS_17_5YR_S0101_metadata.csv', 'ACS_17_5YR_S0501_metadata.csv', 'ACS_17_5YR_S0801_metadata.csv', 'ACS_17_5YR_S0802_metadata.csv', 'ACS_17_5YR_S0901_metadata.csv', 'ACS_17_5YR_S1101_metadata.csv', 'ACS_17_5YR_S1201_metadata.csv', 'ACS_17_5YR_S1301_metadata.csv', 'ACS_17_5YR_S1401_metadata.csv', 'ACS_17_5YR_S1501_metadata.csv', 'ACS_17_5YR_S1502_metadata.csv', 'ACS_17_5YR_S1601_metadata.csv', 'ACS_17_5YR_S1602_metadata.csv', 'ACS_17_5YR_S1603_metadata.csv', 'ACS_17_5YR_S1701_metadata.csv', 'ACS_17_5YR_S1810_metadata.csv', 'ACS_17_5YR_S1901_metadata.csv', 'ACS_17_5YR_S1902_metadata.csv', 'ACS_17_5YR_S1903_metadata.csv', 'ACS_17_5YR_S2001_metadata.csv', 'ACS_17_5YR_S2101_metadata.csv', 'ACS_17_5YR_S2201_metadata.csv', 'ACS_17_5YR_S2301_metadata.csv', 'ACS_17_5YR_S2302_metadata.csv', 'ACS_17_5YR_S2303_metadata.csv', 'ACS_17_5YR_S2501_metadata.csv', 'ACS_17_5YR_S2801_metadata.csv', 'ACS_17_5YR_S2802_metadata.csv']

In [7]:
#create lookup table, read first two lines
aff_lookup = {}
for x in aff_txt:
    with open(aff_path+"/"+x) as myfile:
        head = [next(myfile).replace('\n','') for x in range(2)]
        aff_lookup[head[0]] = head[1].lower().replace(':', '').replace(';', '')\
              .replace('(', '').replace(')', '').replace('-','')\
              .strip().replace(' ', '_')
#remove erroreous extraction
aff_lookup.pop('', None)
print(aff_lookup)

{'B01001': 'sex_by_age', 'B28002': 'presence_and_types_of_internet_subscriptions_in_household', 'B28003': 'presence_of_a_computer_and_type_of_internet_subscription_in_household', 'B28004': 'household_income_in_the_last_12_months_in_2017_inflationadjusted_dollars_by_presence_and_type_of_internet_subscription_in_household', 'B28005': 'age_by_presence_of_a_computer_and_types_of_internet_subscription_in_household', 'B28006': 'educational_attainment_by_presence_of_a_computer_and_types_of_internet_subscription_in_household', 'B28007': 'labor_force_status_by_presence_of_a_computer_and_types_of_internet_subscription_in_household', 'B28008': 'presence_of_a_computer_and_type_of_internet_subscription_in_household', 'B28011': 'internet_subscriptions_in_household', 'B99281': 'allocation_of_household_internet_access', 'B99283': 'allocation_of_household_internet_subscription_type', 'DP02': 'selected_social_characteristics_in_the_united_states', 'S0101': 'age_and_sex', 'S0501': 'selected_characteristics_of_the_native_and_foreignborn_populations', 'S0801': 'commuting_characteristics_by_sex', 'S0802': 'means_of_transportation_to_work_by_selected_characteristics', 'S0901': 'children_characteristics', 'S1101': 'households_and_families', 'S1201': 'marital_status', 'S1301': 'fertility', 'S1401': 'school_enrollment', 'S1501': 'educational_attainment', 'S1502': "field_of_bachelor's_degree_for_first_major", 'S1601': 'language_spoken_at_home', 'S1602': 'limited_english_speaking_households', 'S1603': 'characteristics_of_people_by_language_spoken_at_home', 'S1701': 'poverty_status_in_the_past_12_months', 'S1810': 'disability_characteristics', 'S1901': 'income_in_the_past_12_months_in_2017_inflationadjusted_dollars', 'S1902': 'mean_income_in_the_past_12_months_in_2017_inflationadjusted_dollars', 'S1903': 'median_income_in_the_past_12_months_in_2017_inflationadjusted_dollars', 'S2001': 'earnings_in_the_past_12_months_in_2017_inflationadjusted_dollars', 'S2101': 'veteran_status', 'S2201': 'food_stamps/supplemental_nutrition_assistance_program_snap', 'S2301': 'employment_status', 'S2302': 'employment_characteristics_of_families', 'S2303': 'work_status_in_the_past_12_months', 'S2501': 'occupancy_characteristics', 'S2801': 'types_of_computers_and_internet_subscriptions', 'S2802': 'types_of_internet_subscriptions_by_selected_characteristics'}

In [8]:
key = list(aff_lookup.keys())[0]
key
meta = [s for s in aff_csv if key in s][0]
print(meta)

ACS_17_5YR_B01001_with_ann.csv

In [34]:
#create clean csv tables for backing-up
for x in aff_lookup.keys():
    meta = [s for s in aff_csv_meta if x in s][0]
    dataset = [s for s in aff_csv if x in s][0]
    print("processing metadata file : {}".format(meta))
    print("processing dataset file : {}".format(dataset))
    colz=[]         #an empty list to store the second column
    with open(aff_path+"/"+meta, 'r') as rf:
        reader = csv.reader(rf, delimiter=',')
        for row in reader:
            colz.append(row[1])
    colz_clean = [x.lower().replace(':', '').replace(';', '')\
                  .replace('(', '').replace(')', '').replace('-','')\
                  .strip().replace(' ', '_') for x in colz]
    print("printing sample cleaned columns {}".format(colz_clean[:5]))
    pd_ = pd.read_csv(aff_path+"/"+dataset,skiprows=1)
    print("table has {} rows".format(len(pd_.index)))
    pd_.columns = colz_clean
    #geography filter for "NYC"
    pd_= pd_[pd_['geography'].str.contains("NYC")]
    pd_['PUMA'] = pd_.id2.astype(str).str[3:].astype(int)
    print("saving file to {}/{}.csv".format(output_path,aff_lookup[x]))
    pd_.to_csv(output_path+"/"+aff_lookup[x].replace('/', '_').replace('/', '_')+".csv",index=False)
    print("-----------------------------------------")

processing metadata file : ACS_17_5YR_B01001_metadata.csv
processing dataset file : ACS_17_5YR_B01001_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/sex_by_age.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B28002_metadata.csv
processing dataset file : ACS_17_5YR_B28002_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/presence_and_types_of_internet_subscriptions_in_household.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B28003_metadata.csv
processing dataset file : ACS_17_5YR_B28003_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/presence_of_a_computer_and_type_of_internet_subscription_in_household.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B28004_metadata.csv
processing dataset file : ACS_17_5YR_B28004_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/household_income_in_the_last_12_months_in_2017_inflationadjusted_dollars_by_presence_and_type_of_internet_subscription_in_household.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B28005_metadata.csv
processing dataset file : ACS_17_5YR_B28005_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/age_by_presence_of_a_computer_and_types_of_internet_subscription_in_household.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B28006_metadata.csv
processing dataset file : ACS_17_5YR_B28006_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/educational_attainment_by_presence_of_a_computer_and_types_of_internet_subscription_in_household.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B28007_metadata.csv
processing dataset file : ACS_17_5YR_B28007_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/labor_force_status_by_presence_of_a_computer_and_types_of_internet_subscription_in_household.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B28008_metadata.csv
processing dataset file : ACS_17_5YR_B28008_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/presence_of_a_computer_and_type_of_internet_subscription_in_household.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B28011_metadata.csv
processing dataset file : ACS_17_5YR_B28011_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/internet_subscriptions_in_household.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B99281_metadata.csv
processing dataset file : ACS_17_5YR_B99281_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'estimate_total__allocated']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/allocation_of_household_internet_access.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_B99283_metadata.csv
processing dataset file : ACS_17_5YR_B99283_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_total', 'estimate_allocated__dialup']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/allocation_of_household_internet_subscription_type.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_DP02_metadata.csv
processing dataset file : ACS_17_5YR_DP02_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'estimate_households_by_type__total_households', 'margin_of_error_households_by_type__total_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/selected_social_characteristics_in_the_united_states.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S0101_metadata.csv
processing dataset file : ACS_17_5YR_S0101_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_total_population', 'total_margin_of_error_total_population']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/age_and_sex.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S0501_metadata.csv
processing dataset file : ACS_17_5YR_S0501_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_total_population', 'total_margin_of_error_total_population']
table has 118 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/selected_characteristics_of_the_native_and_foreignborn_populations.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S0801_metadata.csv
processing dataset file : ACS_17_5YR_S0801_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_workers_16_years_and_over', 'total_margin_of_error_workers_16_years_and_over']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/commuting_characteristics_by_sex.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S0802_metadata.csv
processing dataset file : ACS_17_5YR_S0802_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_workers_16_years_and_over', 'total_margin_of_error_workers_16_years_and_over']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/means_of_transportation_to_work_by_selected_characteristics.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S0901_metadata.csv
processing dataset file : ACS_17_5YR_S0901_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_children_under_18_years_in_households', 'total_margin_of_error_children_under_18_years_in_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/children_characteristics.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1101_metadata.csv
processing dataset file : ACS_17_5YR_S1101_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_total_households', 'total_margin_of_error_total_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/households_and_families.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1201_metadata.csv
processing dataset file : ACS_17_5YR_S1201_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_population_15_years_and_over', 'total_margin_of_error_population_15_years_and_over']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/marital_status.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1301_metadata.csv
processing dataset file : ACS_17_5YR_S1301_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_women_15_to_50_years', 'total_margin_of_error_women_15_to_50_years']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/fertility.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1401_metadata.csv
processing dataset file : ACS_17_5YR_S1401_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_population_3_years_and_over_enrolled_in_school', 'total_margin_of_error_population_3_years_and_over_enrolled_in_school']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/school_enrollment.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1501_metadata.csv
processing dataset file : ACS_17_5YR_S1501_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_population_18_to_24_years', 'total_margin_of_error_population_18_to_24_years']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/educational_attainment.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1502_metadata.csv
processing dataset file : ACS_17_5YR_S1502_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', "total_estimate_total_population_25_years_and_over_with_a_bachelor's_degree_or_higher", "total_margin_of_error_total_population_25_years_and_over_with_a_bachelor's_degree_or_higher"]
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/field_of_bachelor's_degree_for_first_major.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1601_metadata.csv
processing dataset file : ACS_17_5YR_S1601_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_population_5_years_and_over', 'total_margin_of_error_population_5_years_and_over']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/language_spoken_at_home.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1602_metadata.csv
processing dataset file : ACS_17_5YR_S1602_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_all_households', 'total_margin_of_error_all_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/limited_english_speaking_households.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1603_metadata.csv
processing dataset file : ACS_17_5YR_S1603_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_total_population_5_years_and_over', 'total_margin_of_error_total_population_5_years_and_over']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/characteristics_of_people_by_language_spoken_at_home.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1701_metadata.csv
processing dataset file : ACS_17_5YR_S1701_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_population_for_whom_poverty_status_is_determined', 'total_margin_of_error_population_for_whom_poverty_status_is_determined']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/poverty_status_in_the_past_12_months.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1810_metadata.csv
processing dataset file : ACS_17_5YR_S1810_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_total_civilian_noninstitutionalized_population', 'total_margin_of_error_total_civilian_noninstitutionalized_population']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/disability_characteristics.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1901_metadata.csv
processing dataset file : ACS_17_5YR_S1901_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'households_estimate_total', 'households_margin_of_error_total']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/income_in_the_past_12_months_in_2017_inflationadjusted_dollars.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1902_metadata.csv
processing dataset file : ACS_17_5YR_S1902_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'number_estimate_all_households', 'number_margin_of_error_all_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/mean_income_in_the_past_12_months_in_2017_inflationadjusted_dollars.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S1903_metadata.csv
processing dataset file : ACS_17_5YR_S1903_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'number_estimate_households', 'number_margin_of_error_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/median_income_in_the_past_12_months_in_2017_inflationadjusted_dollars.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2001_metadata.csv
processing dataset file : ACS_17_5YR_S2001_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_population_16_years_and_over_with_earnings', 'total_margin_of_error_population_16_years_and_over_with_earnings']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/earnings_in_the_past_12_months_in_2017_inflationadjusted_dollars.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2101_metadata.csv
processing dataset file : ACS_17_5YR_S2101_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_civilian_population_18_years_and_over', 'total_margin_of_error_civilian_population_18_years_and_over']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/veteran_status.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2201_metadata.csv
processing dataset file : ACS_17_5YR_S2201_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_households', 'total_margin_of_error_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/food_stamps/supplemental_nutrition_assistance_program_snap.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2301_metadata.csv
processing dataset file : ACS_17_5YR_S2301_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_population_16_years_and_over', 'total_margin_of_error_population_16_years_and_over']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/employment_status.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2302_metadata.csv
processing dataset file : ACS_17_5YR_S2302_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_families', 'total_margin_of_error_families']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/employment_characteristics_of_families.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2303_metadata.csv
processing dataset file : ACS_17_5YR_S2303_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_population_16_to_64_years', 'total_margin_of_error_population_16_to_64_years']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/work_status_in_the_past_12_months.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2501_metadata.csv
processing dataset file : ACS_17_5YR_S2501_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'occupied_housing_units_estimate_occupied_housing_units', 'occupied_housing_units_margin_of_error_occupied_housing_units']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/occupancy_characteristics.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2801_metadata.csv
processing dataset file : ACS_17_5YR_S2801_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_total_households', 'total_margin_of_error_total_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/types_of_computers_and_internet_subscriptions.csv
-----------------------------------------
processing metadata file : ACS_17_5YR_S2802_metadata.csv
processing dataset file : ACS_17_5YR_S2802_with_ann.csv
printing sample cleaned columns ['id', 'id2', 'geography', 'total_estimate_total_population_in_households', 'total_margin_of_error_total_population_in_households']
table has 145 rows
saving file to C:\Users\Marvin\Google Drive\NYU CUSP Capstone 2019\Marvin\Input\aff_batch1\clean_batch1/types_of_internet_subscriptions_by_selected_characteristics.csv
-----------------------------------------

In [76]:
colz=[]         #an empty list to store the second column
with open(aff_path+"/"+'ACS_17_5YR_B08201_metadata.csv', 'r') as rf:
    reader = csv.reader(rf, delimiter=',')
    for row in reader:
        colz.append(row[1])
colz_clean = [x.lower().replace(':', '').replace(';', '')\
              .replace('(', '').replace(')', '').replace('-','')\
              .strip().replace(' ', '_') for x in colz]
#print(colz_clean)
test_pd = pd.read_csv(aff_path+"/"+'ACS_17_5YR_B08201_with_ann.csv',skiprows=1)

In [58]:
test_pd.columns = colz_clean

In [59]:
test_pd.head()

,id,id2,geography,estimate_total,margin_of_error_total,estimate_total__no_vehicle_available,margin_of_error_total__no_vehicle_available,estimate_total__1_vehicle_available,margin_of_error_total__1_vehicle_available,estimate_total__2_vehicles_available,...,estimate_total__4ormoreperson_household__no_vehicle_available,margin_of_error_total__4ormoreperson_household__no_vehicle_available,estimate_total__4ormoreperson_household__1_vehicle_available,margin_of_error_total__4ormoreperson_household__1_vehicle_available,estimate_total__4ormoreperson_household__2_vehicles_available,margin_of_error_total__4ormoreperson_household__2_vehicles_available,estimate_total__4ormoreperson_household__3_vehicles_available,margin_of_error_total__4ormoreperson_household__3_vehicles_available,estimate_total__4ormoreperson_household__4_or_more_vehicles_available,margin_of_error_total__4ormoreperson_household__4_or_more_vehicles_available
0,1400000US36061000100,36061000100,"Census Tract 1, New York County, New York",0,11,0,11,0,11,0,...,0,11,0,11,0,11,0,11,0,11
1,1400000US36061000201,36061000201,"Census Tract 2.01, New York County, New York",985,79,907,88,64,48,14,...,190,77,0,11,6,9,0,11,0,11
2,1400000US36061000202,36061000202,"Census Tract 2.02, New York County, New York",3434,183,2544,236,890,205,0,...,245,92,268,104,0,16,0,16,0,16
3,1400000US36061000500,36061000500,"Census Tract 5, New York County, New York",0,11,0,11,0,11,0,...,0,11,0,11,0,11,0,11,0,11
4,1400000US36061000600,36061000600,"Census Tract 6, New York County, New York",4098,255,3447,372,626,278,25,...,539,229,115,110,25,39,0,18,0,18

In [93]:
url2 = "https://www1.nyc.gov/assets/finance/downloads/pdf/rolling_sales/neighborhood_sales/2017_citywide_sale.xlsx"
urllib.urlretrieve(url2, "test.xls")
file="/home/jinalklaulitz/Documents/ML_4_cities/Project/test.xls"
test_pd = pd.read_excel(file,skiprows=4)

In [94]:
test_pd.head()

,BOROUGH,BUILDING CLASS CATEGORY,NUMBER OF SALES,MINIMUM SALE PRICE,AVERAGE SALE PRICE,MEDIAN SALE PRICE,MAXIMUM SALE PRICE
0,Manhattan,01 ONE FAMILY HOMES,89,200000.0,8235346.0,6350000.0,41000000.0
1,Manhattan,02 TWO FAMILY HOMES,74,424797.0,5620562.0,3725000.0,43500000.0
2,Manhattan,03 THREE FAMILY HOMES,40,816425.0,5684533.0,2965000.0,27400000.0
3,Bronx,01 ONE FAMILY HOMES,970,200000.0,499060.0,425000.0,12303058.0
4,Bronx,02 TWO FAMILY HOMES,1409,200000.0,523501.0,512000.0,5400000.0

In [57]:
#create base table
base_table_file = list(aff_lookup.values())[0]
pd_ = pd.read_csv(output_path+"/"+base_table_file.replace('/', '_').replace('/', '_')+".csv")
base_table = pd_[['id','id2','geography']]

for x in aff_lookup.keys():
    print("processing dataset : {}".format(aff_lookup[x].replace('/', '_').replace('/', '_')))
    pd_ = pd.read_csv(output_path+"/"+aff_lookup[x].replace('/', '_').replace('/', '_')+".csv")
    drop_cols=[x for x in pd_.columns.get_values() if "margin_of_error" in x]
    #convert '' to null
    pd_.replace('', np.nan,inplace=True)
    #convert (X) to null
    pd_.replace('(X)', np.nan,inplace=True)
    #checks for any NaN values and returns column name
    drop_cols.extend(pd_.columns[pd_.isnull().any()].tolist())
    pd_=pd_.drop(drop_cols,axis=1)
    cols_to_use = pd_.columns.difference(base_table.columns)
    base_table = base_table.merge(pd_[cols_to_use],left_index=True, right_index=True, how='outer')
    print("-----------------------------------------")

processing dataset : sex_by_age
-----------------------------------------
processing dataset : presence_and_types_of_internet_subscriptions_in_household
-----------------------------------------
processing dataset : presence_of_a_computer_and_type_of_internet_subscription_in_household
-----------------------------------------
processing dataset : household_income_in_the_last_12_months_in_2017_inflationadjusted_dollars_by_presence_and_type_of_internet_subscription_in_household
-----------------------------------------
processing dataset : age_by_presence_of_a_computer_and_types_of_internet_subscription_in_household
-----------------------------------------
processing dataset : educational_attainment_by_presence_of_a_computer_and_types_of_internet_subscription_in_household
-----------------------------------------
processing dataset : labor_force_status_by_presence_of_a_computer_and_types_of_internet_subscription_in_household
-----------------------------------------
processing dataset : presence_of_a_computer_and_type_of_internet_subscription_in_household
-----------------------------------------
processing dataset : internet_subscriptions_in_household
-----------------------------------------
processing dataset : allocation_of_household_internet_access
-----------------------------------------
processing dataset : allocation_of_household_internet_subscription_type
-----------------------------------------
processing dataset : selected_social_characteristics_in_the_united_states
-----------------------------------------
processing dataset : age_and_sex
-----------------------------------------
processing dataset : selected_characteristics_of_the_native_and_foreignborn_populations
-----------------------------------------
processing dataset : commuting_characteristics_by_sex
-----------------------------------------
processing dataset : means_of_transportation_to_work_by_selected_characteristics
-----------------------------------------
processing dataset : children_characteristics
-----------------------------------------
processing dataset : households_and_families
-----------------------------------------
processing dataset : marital_status
-----------------------------------------
processing dataset : fertility
-----------------------------------------
processing dataset : school_enrollment
-----------------------------------------
processing dataset : educational_attainment
-----------------------------------------
processing dataset : field_of_bachelor's_degree_for_first_major
-----------------------------------------
processing dataset : language_spoken_at_home
-----------------------------------------
processing dataset : limited_english_speaking_households
-----------------------------------------
processing dataset : characteristics_of_people_by_language_spoken_at_home
-----------------------------------------
processing dataset : poverty_status_in_the_past_12_months
-----------------------------------------
processing dataset : disability_characteristics
-----------------------------------------
processing dataset : income_in_the_past_12_months_in_2017_inflationadjusted_dollars
-----------------------------------------
processing dataset : mean_income_in_the_past_12_months_in_2017_inflationadjusted_dollars
-----------------------------------------
processing dataset : median_income_in_the_past_12_months_in_2017_inflationadjusted_dollars
-----------------------------------------
processing dataset : earnings_in_the_past_12_months_in_2017_inflationadjusted_dollars
-----------------------------------------
processing dataset : veteran_status
-----------------------------------------
processing dataset : food_stamps_supplemental_nutrition_assistance_program_snap
-----------------------------------------
processing dataset : employment_status
-----------------------------------------
processing dataset : employment_characteristics_of_families
-----------------------------------------
processing dataset : work_status_in_the_past_12_months
-----------------------------------------
processing dataset : occupancy_characteristics
-----------------------------------------
processing dataset : types_of_computers_and_internet_subscriptions
-----------------------------------------
processing dataset : types_of_internet_subscriptions_by_selected_characteristics
-----------------------------------------

In [58]:
base_table.to_csv(output_path+"/demographics_base_table_batch1.csv",index=False)

In [44]:
base_table.head()

,id_x,id2,geography_x,id_y,geography_y,estimate_total_x,estimate_male,estimate_male__under_5_years,estimate_male__5_to_9_years,estimate_male__10_to_14_years,...,no_computer_in_household_estimate_employment_status__civilian_population_16_years_and_over__in_labor_force__unemployed,percent_no_computer_in_household_estimate_employment_status__civilian_population_16_years_and_over__in_labor_force__unemployed,total_estimate_employment_status__civilian_population_16_years_and_over__not_in_labor_force,with_a_computer___broadband_internet_subscription_estimate_employment_status__civilian_population_16_years_and_over__not_in_labor_force,with_a_computer___percent__broadband_internet_subscription_estimate_employment_status__civilian_population_16_years_and_over__not_in_labor_force,with_a_computer___without_an_internet_subscription_estimate_employment_status__civilian_population_16_years_and_over__not_in_labor_force,with_a_computer___percent_without_an_internet_subscription_estimate_employment_status__civilian_population_16_years_and_over__not_in_labor_force,no_computer_in_household_estimate_employment_status__civilian_population_16_years_and_over__not_in_labor_force,percent_no_computer_in_household_estimate_employment_status__civilian_population_16_years_and_over__not_in_labor_force,PUMA_y
0,7950000US3603701,3603701,"NYC-Bronx Community District 8--Riverdale, Fie...",7950000US3603701,"NYC-Bronx Community District 8--Riverdale, Fie...",111182,52452,4780,3346,3167,...,372,7.7,27805,20505,73.7,1759,6.3,5341,19.2,3701
1,7950000US3603702,3603702,"NYC-Bronx Community District 12--Wakefield, Wi...",7950000US3603702,"NYC-Bronx Community District 12--Wakefield, Wi...",147447,67432,4601,4412,4591,...,831,10.0,41997,29557,70.4,4689,11.2,7435,17.7,3702
2,7950000US3603703,3603703,"NYC-Bronx Community District 10--Co-op City, P...",7950000US3603703,"NYC-Bronx Community District 10--Co-op City, P...",122586,56759,3183,3629,3674,...,170,3.5,37909,26363,69.5,3479,9.2,7921,20.9,3703
3,7950000US3603704,3603704,NYC-Bronx Community District 11--Pelham Parkwa...,7950000US3603704,NYC-Bronx Community District 11--Pelham Parkwa...,129590,62190,4212,4012,4085,...,499,7.2,36354,25041,68.9,3833,10.5,7270,20.0,3704
4,7950000US3603705,3603705,"NYC-Bronx Community District 3 & 6--Belmont, C...",7950000US3603705,"NYC-Bronx Community District 3 & 6--Belmont, C...",174875,81190,7271,6948,6264,...,1125,11.2,53351,30660,57.5,9615,18.0,12978,24.3,3705

In [48]:
fix_x = pd.read_csv(output_path+"/households_and_families.csv")

In [53]:
sample_col = fix_x.replace('(X)', np.nan)['nonfamily_household_estimate_age_of_own_children__households_with_own_children_of_the_householder_under_18_years__6_to_17_years_only']

In [54]:
print(sample_col)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
40   NaN
41   NaN
42   NaN
43   NaN
44   NaN
45   NaN
46   NaN
47   NaN
48   NaN
49   NaN
50   NaN
51   NaN
52   NaN
53   NaN
54   NaN
Name: nonfamily_household_estimate_age_of_own_children__households_with_own_children_of_the_householder_under_18_years__6_to_17_years_only, dtype: float64